# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    # IMPORT LIBRARIES
    import polars as pl
    import pygwalker as pyg
    import plotly.express as px
    from pmdarima import auto_arima
    import psycopg2
    import pandas as pd
    from statsmodels.tsa.stattools import adfuller
    from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
    from statsmodels.tsa.statespace.sarimax import SARIMAX
    from plotly.subplots import make_subplots

    from src.db_connect import ps_connect


    from keplergl import KeplerGl
    from shinywidgets import render_widget, render_plotly
    import matplotlib.pyplot as plt
    from datetime import datetime
    import plotly.graph_objects as go
    from ipyleaflet import Map, Polyline, CircleMarker, Marker
    from shiny import render, reactive, ui
    # from shiny.express import render, ui,  input

    from datetime import date
    import base64
    import calendar
    from dateutil.relativedelta import relativedelta
    from IPython.display import HTML
    import json

    # from sklearn.metrics import mean_absolute_error, mean_squared_error

    # ========================================================================

    # CONNECT TO DATABASE AND LOAD DATA
    conn = ps_connect()
    cursor = conn.cursor()

    # ========================================================================

    # AIRPORT'S LOCATIONS
    query = """SELECT 
            name, latitude_deg, longitude_deg, iso_country, icao_code, iata_code
            FROM airports
            WHERE iata_code IS NOT NULL"""
    df_airports_all = pl.read_database(query, conn)
    df_airports = df_airports_all.select(pl.col("name"), pl.col("latitude_deg"), pl.col("longitude_deg"), pl.col("iata_code"))
    # tromso_airport = df_airports_all.filter(pl.col("iata_code") == "TOS").select(pl.col("name").first())
    # print(tromso_airport)
    # AIRPORT'S CODES
    # query = " select icao_code, iata_code, iso_country from airports where icao_code is not null"
    df_airports_code = df_airports_all.select(pl.col("icao_code"), pl.col("iata_code"), pl.col("iso_country"), pl.col("name"))

    # ========================================================================

    # SSB AIRPORT MONTHLY TRAFFIC + IATA CODE + ISO COUNTRY
    query = "SELECT * from ssb_airport_monthly_traffic"
    df_airport_monthly_traffic = pl.read_database(query, conn)
    df_airport_monthly_traffic =df_airport_monthly_traffic.join(
        df_airports_code,
        left_on="airport_icao_code", 
        right_on="icao_code"
    )

    # ========================================================================

    # AVINOR FLIGHTS + ISO_COUNTRY + AIRPORTS CODES
    query = """SELECT  date_time_of_departure, departure_airport_iata, 
     date_time_of_arrival,arrival_airport_iata,
      aircraft_type, seats from avinor_flights"""
    df_avinor_all = pl.read_database(query, conn)

    # ========================================================================

    # CONSTANTS FOR AVINOR
    START_DATE_AVINOR = date(2026, 1, 1)
    END_DATE_AVINOR = date(2026, 9, 30)
    LAST_MONTH_AVINOR = END_DATE_AVINOR.replace(day=1)

    #CONSTANTS FOR SSB
    START_DATE_SSB = date(2020, 1, 1)
    END_DATE_SSB = (
        df_airport_monthly_traffic
        .select(pl.col("date").max())
        .item()
    )
    LAST_YEAR_SSB = END_DATE_SSB  - relativedelta(years=1)

    # ========================================================================

    # PREPARE AVINOR DATA FOR KEPLER GL 
    # WE TACE LON_DEG LAT_DEG FROM AIRPORTS DATASET AND 
    # JOIN WITH AVINOR DATASET TO GET THE LOCATIONS OF DEPARTURE AND ARRIVAL AIRPORTS
    df_avinor_kepler = df_avinor_all.select(pl.col("date_time_of_departure").dt.date().alias("dep_date"),
     pl.col("departure_airport_iata"), pl.col("date_time_of_arrival").dt.date().alias("arr_date"), pl.col("arrival_airport_iata" ))

    df_dep = df_airports.rename({
        "latitude_deg": "dep_lat",
        "longitude_deg": "dep_lon",
        "name":"dep_name"
    })

    df_arr = df_airports.rename({
        "latitude_deg": "arr_lat",
        "longitude_deg": "arr_lon",
        "name":"arr_name"
    })
    df_avinor_kepler = (
        df_avinor_kepler
        .join(df_dep, left_on="departure_airport_iata", right_on="iata_code")
        .join(df_arr, left_on="arrival_airport_iata", right_on="iata_code")
    )
    df_avinor_kepler = df_avinor_kepler.rename({
        "departure_airport_iata": "dep_iata",
        "arrival_airport_iata": "arr_iata"
    })

    # ========================================================================

    # WE NEED ICAO CODE AND ISO COUNTRY TO DETERMINE IF FLIGHT IS DOMESTIC OR INTERNATIONAL
    # JOIN AVINOR DATA WITH AIRPORTS CODES 
    df_avinor = df_avinor_all.join(
        df_airports_code,
        left_on="departure_airport_iata",
        right_on="iata_code",
        suffix="_departure"
    ).join(
        df_airports_code,
        left_on="arrival_airport_iata",
        right_on="iata_code",
        suffix="_arrival"
    )

    # ========================================================================

    # UI LIST OF NORWEGIAN AIRPORTS FOR SELECT INPUT
    airports_list = (df_airport_monthly_traffic.filter(pl.col("iso_country")=="NO")).select("name", "iata_code").unique().sort("name")
    ui.input_select("airport", "Airport:",
                    choices=dict(zip(airports_list["iata_code"].to_list(), airports_list["name"].to_list())),
                    selected="TOS")

    # ========================================================================

    @reactive.calc
    def airport():
        airport_name = input.airport()
        return airport_name
        # iata_code = (
        #     df_airport_monthly_traffic
        #     .filter(pl.col("name") == airport_name)
        #     .select(pl.col("iata_code").first())
        #     .item()
        # )
        # return iata_code

    # ========================================================================

    # ADD SEAT OCCUPANCY TO SSB DATA (PASSENGERS/SEATS) AND FLIGHT TYPE (INTERNATIONAL/DOMESTIC + ARRIVAL/DEPARTURE)
    df_ssb = (
        df_airport_monthly_traffic
        .filter(
            (pl.col("seats").is_not_null()) &
            (pl.col("passengers").is_not_null()) &
            (pl.col("seats") > 0) &
            (pl.col("passengers") > 0)
        )
        .with_columns(
            (pl.col("passengers") / pl.col("seats") ).alias("seat_occupancy")
        )
        .with_columns(
            ( pl.col("international_domestic") + pl.col("arrival_departure")).alias("flight_type")
        )
    )
    # READ AIRCRAFT SEATS BY TYPE 
    query = "select * from aircraft_types_seats"
    df_aircraft_seats_by_type = pl.read_database(query, conn)
    df_aircraft_seats_by_type = df_aircraft_seats_by_type.select(pl.col("type"), pl.col("seats_max"))

    # JOIN SEATS TO AVINOR DATA TO FILL OUT EMPTY SEATS VALUES IN AVINOR DATASET 
    # SEATS IN AVINOR WAS CALCULATED FROM CONFIGURATION OF AIRCRAFT
    # SOME AIRLINES HAS OWN TYPES OF CONFIGURATION THAT MAKES IMPOSSIBLE TO FIND SEATS

    df_avinor = df_avinor.join(
        df_aircraft_seats_by_type,
        left_on="aircraft_type",
        right_on="type",
        how="left"
    )
    # COALESCE SEATS AND SEATS_RIGHT TO TOTAL_SEATS COLUMN
    df_avinor = df_avinor.with_columns(
       pl.coalesce(pl.col("seats"), pl.col("seats_max")).alias("total_seats")
    )

    # ========================================================================

    # FILTER DATA FROM 2023 TO 2026
    # FIND SUM OF PASSENGERS BY MONTH FOR FROM SSB DATA
    # THIS IS USED IN SARIMA FORECAST MODELS 
    @reactive.calc
    def filtered_ssb_data():
        last3_years = END_DATE_SSB - relativedelta(years=3)
        df_Ssb = (
        df_ssb
            .filter(
                # Filter for TOS (ENTC) and valid data from 2020 to 2026
                (pl.col("date").cast(pl.Date).is_between(
                   last3_years,
                   END_DATE_SSB
                )) &
                (pl.col("passengers") > 10) &
                (pl.col("iata_code") == airport())
            )
            .sort("date")
            .group_by_dynamic( index_column="date", every="1mo", closed="left")
            .agg(pl.col("passengers").sum(), pl.col("seats").sum(), pl.col("flights").sum())

        )
        return df_Ssb

    # FILTER DATA FROM 2020 TO 2026 AND CONVERT TO PANDAS FOR PLOTLY
    @reactive.calc
    def filtered_ssb_data_pd( ):
        df_Ssb = (
        df_ssb
            .filter(
                # Filter for TOS (ENTC) and valid data from 2020 to 2026
                (pl.col("date").cast(pl.Date).is_between(
                   START_DATE_SSB,
                   END_DATE_SSB
                )) &
                (pl.col("passengers") > 10) &
                (pl.col("iata_code") == airport())
            )
            .sort("date")
            .group_by("date")
            .agg(pl.col("passengers").sum())
        )
        df_pd = df_Ssb.to_pandas()
        return df_pd

    # ========================================================================

    # FILTER SSB DATA FROM 2025.01.06 TO 2025.06.01 
    # FIX YEAR TO ENABLE JOIN WITH AVINOR DATA (ADD 1 YEAR TO DATE)
    # USED FOR FORECAST BASED ON SEATS OCCUPANCY 
    @reactive.calc
    def occupancy_by_type_2025():
        df_occupancy_by_type_2025 = (
            df_ssb
            .filter(
                (pl.col("date").cast(pl.Date).is_between(
                    LAST_YEAR_SSB,
                    END_DATE_SSB)) &
                (pl.col("iata_code") == airport()) 
            )
            .with_columns(
                # ADD 1 YEAR TO DATE TO MATCH WITH AVINOR DATA 
                pl.date( pl.col("date").dt.year() + 1 , pl.col("date").dt.month(), 1)
            )
            .rename({"date": "date_pred"})
            .select("date_pred", "flight_type", "seat_occupancy")
        )
        return df_occupancy_by_type_2025

    # ========================================================================

    # FILTER AVINOR DATA FOR SELECTED AIRPORT AND DATES (FROM 2026.03.01 TO 2026.08.31)
    @reactive.calc
    def avinor_data():
        start_date = END_DATE_SSB + relativedelta(months=1)
        df_Avinor = (
            df_avinor
            .filter(
                (pl.col("date_time_of_departure").cast(pl.Date).is_between(
                    start_date,
                    END_DATE_AVINOR
                )) &
                (pl.col("date_time_of_arrival").cast(pl.Date).is_between(
                    start_date,
                    END_DATE_AVINOR
                )) &
                (
                    (pl.col("departure_airport_iata") == airport()) |
                    (pl.col("arrival_airport_iata") == airport())
                )
            ))
        # Add flight_type column: DD, ID, DA, IA
        df_Avinor = df_Avinor.with_columns(
            pl.when((pl.col("departure_airport_iata") == airport()) & (pl.col("iso_country_arrival") == "NO"))
            .then(pl.lit("DD"))
            .when((pl.col("departure_airport_iata") == airport()) & (pl.col("iso_country_arrival") != "NO"))
            .then(pl.lit("ID"))
            .when((pl.col("arrival_airport_iata") == airport()) & (pl.col("iso_country") == "NO"))
            .then(pl.lit("DA"))
            .when((pl.col("arrival_airport_iata") == airport()) & (pl.col("iso_country") != "NO"))
            .then(pl.lit("IA"))
            .otherwise(pl.lit(None))
            .alias("flight_type")
        )
        # BRING TO A SAME DATE FORMAT (YEAR-MONTH-01) 
        # AND GROUP BY MONTH AND FLIGHT TYPE TO GET TOTAL SEATS BY MONTH AND FLIGHT TYPE
        df_Avinor = (df_Avinor.with_columns(
                pl.when(pl.col("departure_airport_iata") == airport())
                .then(pl.col("date_time_of_departure").cast(pl.Date))
                .otherwise(pl.col("date_time_of_arrival").cast(pl.Date))
                .alias("date")
            )
            .with_columns(
                pl.date(pl.col("date").dt.year(), pl.col("date").dt.month(), 1).alias("date_pred")
            )
            .group_by("date_pred", "flight_type")
            .agg(pl.col("total_seats").sum(), pl.count().alias("flights_count"))
            .sort("date_pred")
            .select("date_pred", "flights_count", "flight_type", "total_seats"))
        return df_Avinor


    # JOIN AVINOR DATA WITH OCCUPANCY BY TYPE TO CALCULATE PREDICTED PASSENGERS (TOTAL_SEATS * SEAT_OCCUPANCY)
    def avinor_data_pred():
        df_Avinor_pred = (
            avinor_data()
            .join(occupancy_by_type_2025(), on=["date_pred", "flight_type"], how="left")
            .with_columns(
                (pl.col("total_seats") * pl.col("seat_occupancy")).alias("pred_passengers")
            )
            .select("date_pred", "flight_type", "total_seats", "seat_occupancy", "pred_passengers")
        )
        # Sum pred_passengers by month (combine all flight types)
        df_Avinor_pd = df_Avinor_pred.to_pandas()
        df_Avinor_monthly = df_Avinor_pd.groupby('date_pred').agg({'pred_passengers': 'sum'}).reset_index()
        df_Avinor_monthly = df_Avinor_monthly[df_Avinor_monthly['pred_passengers'] > 0]

        return df_Avinor_monthly


    # ========================================================================

    # SARIMA MODEL WITH EXOGENOUS VARIABLES (SEATS AND FLIGHTS)
    @reactive.calc
    def sarima_model():
    
        df = filtered_ssb_data()  

        passengers_data = df.select(["date","passengers"]).to_pandas().set_index("date")
        passengers_data = passengers_data.asfreq("MS")    

        exog_data = df.select(["date", "seats", "flights"]).to_pandas().set_index("date")
        exog_data = exog_data.sort_index().asfreq("MS")

        # result = adfuller(passengers_data)
        # if result[1] > 0.05:
        #     d_param = 1
        # else:
        #     d_param = 0

        # USE AUTO_NODEL TO FIND BEST SARIMA PARAMETERS
        auto_model = auto_arima(
            passengers_data,
            exogenous=exog_data,
            seasonal=True,
            m=12,
            d=None,  
            D=None,
            max_p=3,
            max_q=3,
            max_P=2,
            max_Q=2,
            trace=True,
            stepwise=True,
            error_action="ignore",
            suppress_warnings=True
        )

        best_order = auto_model.order
        best_seasonal = auto_model.seasonal_order
        # USE FOUND PARAMETERS IN SARIMAX
        model = SARIMAX(
            passengers_data,
            exog=exog_data,
            order=best_order,
            seasonal_order=best_seasonal,

        )
        return model.fit(disp=False)


    # ========================================================================

    # MAKE SARIMA FORECAST AND PREPARE DATA FOR PLOTLY
    @reactive.calc
    def sarima_forecast_data():
        try:
            model_result = sarima_model()

            # TAKE EXOGENOUS VARIABLES FOR FORECAST PERIOD FROM AVINOR DATASET (SEATS AND FLIGHTS BY MONTH)
            future_values = (avinor_data().group_by("date_pred")
            .agg(pl.col("total_seats").sum().alias("seats"), pl.col("flights_count").sum().alias("flights")).rename({
                "date_pred": "date"
            }))
            exog_future = future_values.select(["date", "seats", "flights"]).to_pandas().set_index("date")
        
            if model_result is None:
                raise ValueError("Model is None")

            # FIND STEPS
            diff = relativedelta(END_DATE_AVINOR, END_DATE_SSB)
            Steps = diff.years * 12 + diff.months

            # MAKE FORECAST
            forecast = model_result.get_forecast(steps=Steps, exog=exog_future)
            forecast_df = forecast.summary_frame()

            # CREATE DATES FOR FORECAST PERIOD
            start_date = END_DATE_SSB + relativedelta(months=1)
            forecast_dates = pd.date_range(
                start= start_date,
                periods=Steps,
                freq="MS"
            )

            forecast_df = forecast_df.copy()
            forecast_df["date"] = forecast_dates

            # save file (safe path)
            # with open("sarima_forecast.txt", "w", encoding="utf-8") as f:
            #     f.write(forecast_df.to_string())

            return forecast_df

        except Exception as e:
            import traceback
            print(traceback.format_exc()) 
            return pd.DataFrame()

    # ========================================================================

    # FILTER + TIME + AIRPORT
    # USED IN CARD AND PLOTS WITH DOMESTIC/INTERNATIONAL AND ARRIVAL/DEPARTURE 
    @reactive.calc
    def ssb_for_last_year():
        df_ssb_given_date_airport = (
            df_ssb
            .filter(
                (pl.col("date").cast(pl.Date).is_between(
                    LAST_YEAR_SSB,
                    END_DATE_SSB
                )) &
                (pl.col("iata_code") == airport())
            )
            .with_columns([
                pl.col("date").dt.year().alias("year"),
                pl.col("date").dt.month().alias("month"),
            ])
        )
        return df_ssb_given_date_airport


    # ========================================================================

    from IPython.display import Image, display
    display(Image("departure.png"))

    # ========================================================================

    ui.markdown(f"**Domestic Departure for {LAST_YEAR_SSB.year}**")
    @render.data_frame
    def dd():
        return make_widget("DD")

    # ========================================================================

    display(Image("arrival.png"))

    # ========================================================================

    ui.markdown(f"**Domestic Arrival for {LAST_YEAR_SSB.year}**")
    @render.data_frame
    def da():
        return make_widget("DA")

    # ========================================================================

    display(Image("departure.png"))

    # ========================================================================

    ui.markdown(f"**International Departure for {LAST_YEAR_SSB.year}**")
    @render.data_frame
    def id():
        return make_widget("ID")

    # ========================================================================

    display(Image("arrival.png"))

    # ========================================================================

    ui.markdown(f"**International Arrival for {LAST_YEAR_SSB.year}**")
    @render.data_frame
    def ia():
        return make_widget("IA")

    # ========================================================================

    def make_widget(flight_type):

        df_DD = ssb_for_last_year().filter(
            pl.col("flight_type") == flight_type
        )

        return pl.DataFrame({
            "Passengers": [df_DD["passengers"].sum()],
            "Flights":    [df_DD["flights"].sum()],
            "Seats":      [df_DD["seats"].sum()]
        })

    # ========================================================================

    # POLT WITH FORECAST AND HISTORICAL DATA
    @render_plotly
    def my_plot():


        fig = go.Figure()
    
        # historical
        ssb = filtered_ssb_data_pd()
        fig.add_trace(go.Scatter(
            x=ssb["date"],
            y=ssb["passengers"],
            mode='lines',
            name='Historical passengers (SSB)',
            line=dict(color='#1f77b4', width=2),
            showlegend=False
        ))
    
        # forecast
        avinor = avinor_data_pred()
        fig.add_trace(go.Scatter(
            x=avinor["date_pred"],
            y=avinor["pred_passengers"],
            mode='lines',
            name='Forecast passengers',
            line=dict(color='#ff7f0e', width=2),
            showlegend=False
        ))
    
        # SARIMA forecast (green dashed line)
        sarima_df = sarima_forecast_data()
        if not sarima_df.empty:
            fig.add_trace(go.Scatter(
                x=sarima_df["date"],
                y=sarima_df["mean"],
                mode='lines',
                name='SARIMA forecast',
                line=dict(color='#2ca02c', width=2),
                showlegend=False
            ))

        # CONNECTION LINES

        last_ssb = ssb.iloc[-1]
        first_sarima = sarima_df.iloc[0]   
        first_avinor = avinor.iloc[0]
        fig.add_trace(go.Scatter(
            x=[last_ssb["date"], first_sarima["date"]],
            y=[last_ssb["passengers"], first_sarima["mean"]],
            mode="lines",
            line=dict(
                color="#2ca02c",
                width=2,
                dash="dash"   
            ),
            showlegend=False
        ))
        fig.add_trace(go.Scatter(
            x=[last_ssb["date"], first_avinor["date_pred"]],
            y=[last_ssb["passengers"], first_avinor["pred_passengers"]],
            mode="lines",
            line=dict(
                color='#ff7f0e',
                width=2,
                dash="dash"   
            ),
            showlegend=False
        ))
        # Add vertical line for today (2026-01-01)
        fig.add_vline(
            x=END_DATE_SSB,
            line_dash='dash',
            line_color='red',
            line_width=2
        )
    
        # Add annotation for the line
        fig.add_annotation(
            x="2026-01-01",
            text=f"Today {END_DATE_SSB}",
            showarrow=False,
            xanchor="right",
            yanchor="top"
        )
    
        # Legend 1: Historical data (top-left)
        fig.add_annotation(
            x=0.02,
            y=0.98,
            xref="paper",
            yref="paper",
            text="<b>Historical Data</b><br><span style='color:#1f77b4'>━ Historical passengers (SSB)</span>",
            showarrow=False,
            xanchor="left",
            yanchor="top",
            bgcolor='rgba(255, 255, 255, 0.8)',
            bordercolor='gray',
            borderwidth=1,
            borderpad=10,
            font=dict(size=10)
        )
    
        # Legend 2: Forecast data (top-right)
        fig.add_annotation(
            x=0.98,
            y=0.98,
            xref="paper",
            yref="paper",
            text="<b>Forecast</b><br><span style='color:#ff7f0e'>━ Forecast passengers</span><br><span style='color:#2ca02c'>╌ SARIMA forecast</span>",
            showarrow=False,
            xanchor="right",
            yanchor="top",
            bgcolor='rgba(255, 255, 255, 0.8)',
            bordercolor='gray',
            borderwidth=1,
            borderpad=10,
            font=dict(size=10)
        )
    
        fig.update_layout(
            autosize=True,
            title='Passengers: Historical vs Forecast',
            xaxis_title='Date',
            yaxis_title='Passengers',
            hovermode='x unified',
            template="plotly_white",
            height=500,
            xaxis=dict(
                range=['2020-01-01', '2028-12-31']
            )
        )
    
        return fig

    # ========================================================================

    # PLOT WITH ANNUAL GRAPH LINE OF PASSENGERS
    @render_plotly
    def render_flights_years():
        last_3_years = (END_DATE_SSB-relativedelta(years=3)).replace(month=1, day=1)
        last_year = (END_DATE_SSB -relativedelta(years=1)).replace(month=12, day=31)
        df_plot = (
        df_ssb.filter((pl.col("date").cast(pl.Date).is_between(
                    last_3_years,
                    last_year
                )) & 
                (pl.col("iata_code") == airport()))
        .with_columns([
            pl.col("date").dt.year().alias("year"),
            pl.col("date").dt.month().alias("month"),
        ])
        .group_by(["year", "month"])
        .agg(
            pl.col("flights").sum().alias("flights_total")
        )
        .sort(["year", "month"])
        )
        month_map = {i: calendar.month_abbr[i].lower() for i in range(1, 13)}
        df_plot = df_plot.with_columns(
            pl.col("month").replace_strict(month_map).alias("month_name")
        )

        df_pd = df_plot.to_pandas()

        fig = px.line(
            df_pd,
            x="month_name",
            y="flights_total",
            color="year",  
            markers=True,
            category_orders={
                "month_name": ["jan","feb","mar","apr","may","jun",
                            "jul","aug","sep","oct","nov","dec"],
                "year": [2024, 2025, 2026]
            },
            title="Total monthly flights by year"
        )

        fig.update_layout(
            autosize=True,
            xaxis_title="Month",
            yaxis_title="Flights",
            legend_title="Year",
            paper_bgcolor="white",
            template="plotly_white"
        )

        return fig

    # ========================================================================

    @render_plotly
    def plot_domestic_internatinal():



        # AGGREGATION

        df_plot = (
            ssb_for_last_year()
            .group_by(["year", "month", "international_domestic"])
            .agg(
                pl.col("flights").sum().alias("flights_total")
            )
            .sort(["year", "month"])
        )


        #  MONTH LABELS

        month_map = {i: calendar.month_abbr[i].lower() for i in range(1, 13)}

        df_plot = df_plot.with_columns(
            pl.col("month").replace_strict(month_map).alias("month_name")
        )



        df_pd = df_plot.to_pandas()

        #  PLOTLY

        fig = px.area(
            df_pd,
            x="month_name",
            y="flights_total",
            color="international_domestic",
            facet_col="year",
            markers=True,
            category_orders={
                "month_name": [
                    "jan","feb","mar","apr","may","jun",
                    "jul","aug","sep","oct","nov","dec"
                ]
            },
            title="Domestic vs International Flights by Month and Year"
        )

        fig.update_layout(
            autosize=True,
            xaxis_title="Month",
            yaxis_title="Flights",
            legend_title="Type",
            paper_bgcolor="white",
            template="plotly_white"
        )

        return fig

    # ========================================================================

    @render_plotly
    def plot_arival_departure_growth():


        df = (
            ssb_for_last_year()
            .with_columns([
                pl.col("date").dt.year().alias("year"),
                pl.col("date").dt.month().alias("month"),
            ])
            .group_by(["year", "month", "arrival_departure"])
            .agg(
                pl.col("passengers").sum().alias("passengers_total")
            )
            .pivot(
                values="passengers_total",
                index=["year", "month"],
                columns="arrival_departure"
            )
            .fill_null(0)
            .with_columns(
                (pl.col("A") - pl.col("D")).alias("diff")
            )
            .sort(["year", "month"])
        )


        month_map = {i: calendar.month_abbr[i].lower() for i in range(1, 13)}

        df = df.with_columns(
            pl.col("month").replace_strict(month_map).alias("month_name")
        )

        df_pd = df.to_pandas()

        fig = px.line(
            df_pd,
            x="month_name",
            y="diff",
            color="year",
            markers=True,
            category_orders={
                "month_name": [
                    "jan","feb","mar","apr","may","jun",
                    "jul","aug","sep","oct","nov","dec"
                ]
            },
            title="Arrival - Departure Passenger Difference"
        )
        fig.add_hline(
        y=0,
        line_dash="dash",
        line_color="red",
        line_width=2
        )
        fig.update_layout(
            autosize=True,
            xaxis_title="Month",
            yaxis_title="Passengers (Arrival - Departure)",
            template="plotly_white"
        )

        return fig

    # ========================================================================

    @render_plotly
    def plot_weekly_traffic():
        df_weekly = (
        df_avinor
        .filter(
            ((pl.col("departure_airport_iata") == airport()) |
            (pl.col("arrival_airport_iata") == airport())) &
            (pl.col("date_time_of_departure").dt.date().is_between(
                LAST_MONTH_AVINOR,
                END_DATE_AVINOR
            ))
        )
        .with_columns(
            pl.col("date_time_of_departure").dt.date().alias("date")
        )
        .group_by("date")
        .agg(
            pl.count().alias("daily_flights")
        )
        .with_columns(
            pl.col("date").dt.strftime("%A").alias("weekday_name"),
            pl.col("date").dt.weekday().alias("weekday")
        )
        .group_by(["weekday_name", "weekday"])
        .agg(
            pl.col("daily_flights").mean().round(0).alias("avg_flights")
        )
        .sort("weekday"))

        # df_weekly.write_csv("weekly.txt")
    
   
        pdf = df_weekly.to_pandas()


        fig = px.bar(
            pdf,
            x="weekday_name",
            y="avg_flights",
            title=f"Average Flights per Weekday for {LAST_MONTH_AVINOR.strftime('%B %Y')}",
            labels={
                "weekday_name": "Day of Week",
                "avg_flights": "Average Flights"
            }
        )
        fig.update_layout(
            xaxis_title="Week day",
            yaxis_title="Flights",
            legend_title="Type",
            paper_bgcolor="white",
            autosize=True,
            template="plotly_white"
        )

        return fig


    # ========================================================================

    @render_plotly
    def plot_hourly_traffic():
        df_hourly = (
            df_avinor
            .filter(
               ( (pl.col("departure_airport_iata") == airport()) |
                (pl.col("arrival_airport_iata") == airport()) ) &
                (pl.col("date_time_of_departure").dt.date().is_between(
                    LAST_MONTH_AVINOR,
                    END_DATE_AVINOR
                ))
            )
            .with_columns([
                pl.col("date_time_of_departure").dt.date().alias("date"),
                pl.col("date_time_of_departure").dt.hour().alias("hour")
            ])
        
            .group_by(["date", "hour"])
            .agg(
                pl.count().alias("hourly_flights")
            )
        
            .group_by("hour")
            .agg(
                pl.col("hourly_flights").mean().alias("avg_flights")
            )
            .sort("hour")
        )

        pdf = df_hourly.to_pandas()

        fig = px.line(
            pdf,
            x="hour",
            y="avg_flights",
            markers=True,
            title=f"Average Flights per Hour of Day for {LAST_MONTH_AVINOR.strftime('%B %Y')}",
            labels={
                "hour": "Hour of Day",
                "avg_flights": "Average Flights"
            }
        )
        fig.update_layout(
            autosize=True,
            xaxis_title="Hour of Day",
            yaxis_title="Flights",
            legend_title="Type",
            template="plotly_white",
            paper_bgcolor="white"
        )
        return fig

    # ========================================================================

    @render_widget
    def plot_flights_ipyleaflet():

        routes = (
        df_avinor_kepler
        .filter(pl.col("dep_iata") == airport())
        .filter(
            pl.col("dep_date").is_between(LAST_MONTH_AVINOR, END_DATE_AVINOR)
        )
        .group_by("arr_iata")
        .agg(
            pl.len().alias("flight_count"),
            pl.first("arr_lat"),
            pl.first("arr_lon")
        )
        )
        dep = (
        df_avinor_kepler
        .filter(pl.col("dep_iata") == airport())
        .select(["dep_lat", "dep_lon"])
        .drop_nulls()
        .head(1)
        .to_pandas()
        )
        dep_lat, dep_lon = dep.iloc[0]

        m = Map(center=(dep_lat, dep_lon), zoom=4)

        # m.add(Marker(location=( df["latitude_deg"][0], df["longitude_deg"][0] )))
        df = routes.to_pandas()
        df["flight_class"] = pd.qcut(
            df["flight_count"],
            q=5,
            labels=False,
            duplicates="drop"
        )

        df["flight_class"] = df["flight_class"].fillna(0).astype(int)

        opacity_map = {
            0: 0.3,
            1: 0.45,
            2: 0.55,
            3: 0.7,
            4: 1.0
        }

        weight_map = {
            0: 1,
            1: 1,
            2: 2,
            3: 2,
            4: 2
        }

        for _, row in df.iterrows():

            if pd.isna(row["arr_lat"]) or pd.isna(row["arr_lon"]):
                continue

            line = Polyline(
                locations=[
                    (dep_lat, dep_lon),
                    (row["arr_lat"], row["arr_lon"])
                ],
                color="blue",
                weight=weight_map[row["flight_class"]],
                opacity=opacity_map[row["flight_class"]],
                lineCap='round'
            )

            m.add(line)

        m.add(CircleMarker(
            location=(dep_lat, dep_lon),
            radius=6,
            color="red"
        ))

        return m

    # ========================================================================

    from keplergl import KeplerGl
    @render_widget
    def display_map():
    
        map_1 = KeplerGl(
            height=600, 
            data={"Intra flights": df_avinor_kepler.to_pandas().dropna()},
            config=map_config
        )
        # map_1.add_data(data=df_avinor.to_pandas().dropna(), name="flights")

        return map_1

    # ========================================================================

    @render.ui

    def display_ssb_traffic():

        html_code =pyg.to_html(df_ssb)
        return ui.HTML(html_code)

    # ========================================================================

    @render.ui

    def display_avinor():

        html_code =pyg.to_html(df_avinor)
        return ui.HTML(html_code)

    # ========================================================================



    return None


_static_assets = ["flights_files","app\\flights_files\\figure-html\\cell-19-output-1.png","app\\flights_files\\figure-html\\cell-21-output-1.png","app\\flights_files\\figure-html\\cell-23-output-1.png","app\\flights_files\\figure-html\\cell-25-output-1.png","app\\flights_files\\libs\\quarto-html\\tippy.css","app\\flights_files\\libs\\quarto-html\\quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css","app\\flights_files\\libs\\quarto-html\\quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css","app\\flights_files\\libs\\bootstrap\\bootstrap-icons.css","app\\flights_files\\libs\\bootstrap\\bootstrap-6a298fde403041579a69b2204f21ed52.min.css","app\\flights_files\\libs\\bootstrap\\bootstrap-dark-6a298fde403041579a69b2204f21ed52.min.css","app\\flights_files\\libs\\clipboard\\clipboard.min.js","app\\flights_files\\libs\\quarto-html\\quarto.js","app\\flights_files\\libs\\quarto-html\\tabsets\\tabsets.js","app\\flights_files\\libs\\quarto-html\\popper.min.js","app\\flights_files\\libs\\quarto-html\\tippy.umd.min.js","app\\flights_files\\libs\\quarto-html\\anchor.min.js","app\\flights_files\\libs\\bootstrap\\bootstrap.min.js","app\\flights_files\\libs\\quarto-dashboard\\quarto-dashboard.js","app\\flights_files\\libs\\quarto-dashboard\\stickythead.js","app\\flights_files\\libs\\quarto-dashboard\\web-components.js","app\\flights_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "flights.html",
    server,
    static_assets=_static_assets,
)
